/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package postTest;

import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.time.*;
import java.time.format.DateTimeFormatter;
import perbankan.*;

/**
 *
 * @author Sultan Firdaus
 */
public class AdminPanel extends javax.swing.JPanel {

    private final MainFrame frame;
    private final Bank bank;

    /**
     * Creates new form AdminPanel
     *
     * @param frame
     * @param bank
     */
    public AdminPanel(MainFrame frame, Bank bank) {
        initComponents();
        this.frame = frame;
        this.bank = bank;
        makeTableListener();
    }

    private void clearFieldsAndSelection() {
        txtNamaAwal.setText("");
        txtNamaAkhir.setText("");
        txtSaldo.setText("");
        labelWarning.setText(" ");
        adminTable.clearSelection();
    }

    private void updateFields() {
        txtNamaAwal.setText(adminTable.getModel().getValueAt(adminTable.getSelectedRow(), 0).toString());
        txtNamaAkhir.setText(adminTable.getModel().getValueAt(adminTable.getSelectedRow(), 1).toString());
        txtSaldo.setText(adminTable.getModel().getValueAt(adminTable.getSelectedRow(), 3).toString());
    }

    private void bindData() {
        for (int i = 0; i < bank.getJumlahNasabah(); i++) {
            adminTable.setValueAt(bank.getNasabah(i).getNamaAwal(), i, 0);
            adminTable.setValueAt(bank.getNasabah(i).getNamaAkhir(), i, 1);
            adminTable.setValueAt(bank.getNasabah(i).getNoRekening(), i, 2);
            adminTable.setValueAt(bank.getNasabah(i).getTabungan().getSaldo(), i, 3);
            adminTable.setValueAt(bank.getNasabah(i).getPin(), i, 4);
        }
    }

    private void makeTableListener() {
        adminTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            boolean isSelected = !adminTable.getSelectionModel().isSelectionEmpty();
            btnAdd.setEnabled(!isSelected);
            btnSave.setEnabled(isSelected);
            btnDelete.setEnabled(isSelected);
            btnResetPin.setEnabled(isSelected);
            txtSaldo.setEnabled(!isSelected);
            if (isSelected) {
                updateFields();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExitAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaAwal = new javax.swing.JTextField();
        txtNamaAkhir = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();
        bankAppLabel = new javax.swing.JLabel();
        btnResetPin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        btnExitAdmin.setText("Exit");
        btnExitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAdminActionPerformed(evt);
            }
        });
        add(btnExitAdmin);
        btnExitAdmin.setBounds(488, 8, 53, 26);
        btnExitAdmin.getAccessibleContext().setAccessibleDescription("");

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Awal", "Nama Akhir", "No Rekening", "Saldo", "Pin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adminTable);
        if (adminTable.getColumnModel().getColumnCount() > 0) {
            adminTable.getColumnModel().getColumn(0).setResizable(false);
            adminTable.getColumnModel().getColumn(1).setResizable(false);
            adminTable.getColumnModel().getColumn(2).setResizable(false);
            adminTable.getColumnModel().getColumn(3).setResizable(false);
            adminTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 193, 534, 210);

        jLabel1.setText("Nama Awal");
        add(jLabel1);
        jLabel1.setBounds(62, 78, 74, 16);

        jLabel2.setText("Nama Akhir");
        add(jLabel2);
        jLabel2.setBounds(62, 116, 74, 16);

        jLabel3.setText("Saldo Awal");
        add(jLabel3);
        jLabel3.setBounds(62, 154, 74, 16);
        add(txtNamaAwal);
        txtNamaAwal.setBounds(154, 73, 238, 26);
        add(txtNamaAkhir);
        txtNamaAkhir.setBounds(154, 111, 238, 26);

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        add(txtSaldo);
        txtSaldo.setBounds(154, 149, 124, 26);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(424, 73, 67, 26);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(424, 111, 67, 26);

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(424, 149, 67, 26);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear);
        btnClear.setBounds(328, 149, 64, 26);

        labelWarning.setForeground(new java.awt.Color(255, 0, 0));
        labelWarning.setText(" ");
        add(labelWarning);
        labelWarning.setBounds(154, 51, 149, 16);

        bankAppLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        bankAppLabel.setText("Bank App");
        add(bankAppLabel);
        bankAppLabel.setBounds(223, 6, 99, 26);

        btnResetPin.setText("Reset Pin");
        btnResetPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPinActionPerformed(evt);
            }
        });
        add(btnResetPin);
        btnResetPin.setBounds(449, 400, 90, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-admin.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 546, 436);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAdminActionPerformed
        clearFieldsAndSelection();
        this.setVisible(false);
        frame.showMainPanel();
    }//GEN-LAST:event_btnExitAdminActionPerformed

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int saldo = txtSaldo.getText().isEmpty() ? 0 : Integer.parseInt(txtSaldo.getText());
        String namaAwal = txtNamaAwal.getText();
        String namaAkhir = txtNamaAkhir.getText();

        if (namaAwal.isEmpty() || namaAkhir.isEmpty()) {
            labelWarning.setText("Isikan Nama!!!");
            return;
        }

        DefaultTableModel tableModel = (DefaultTableModel) adminTable.getModel();
        int rowCount = tableModel.getRowCount();
        String formattedTime = LocalTime.now().format(DateTimeFormatter.ofPattern("HH-mm-ss"));

        bank.tambahNasabah(namaAwal, namaAkhir, formattedTime, "123456");
        bank.getNasabah(rowCount).setTabungan(new Tabungan(saldo));
        Object[] newRowData = {bank.getNasabah(rowCount).getNamaAwal(),
            bank.getNasabah(rowCount).getNamaAkhir(),
            bank.getNasabah(rowCount).getNoRekening(),
            bank.getNasabah(rowCount).getTabungan().getSaldo(),
            bank.getNasabah(rowCount).getPin()
        };
        tableModel.addRow(newRowData);

        clearFieldsAndSelection();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFieldsAndSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = adminTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) adminTable.getModel();

        bank.hapusNasabah(selectedRow);
        tableModel.removeRow(selectedRow);

        clearFieldsAndSelection();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int selectedRow = adminTable.getSelectedRow();
        String newNamaAwal = txtNamaAwal.getText();
        String newNamaAkhir = txtNamaAkhir.getText();

        if (newNamaAwal.isEmpty() || newNamaAkhir.isEmpty()) {
            labelWarning.setText("Isikan Nama!!!");
            return;
        }

        bank.getNasabah(selectedRow).setNamaAwal(newNamaAwal);
        bank.getNasabah(selectedRow).setNamaAkhir(newNamaAkhir);
        adminTable.setValueAt(bank.getNasabah(selectedRow).getNamaAwal(), selectedRow, 0);
        adminTable.setValueAt(bank.getNasabah(selectedRow).getNamaAkhir(), selectedRow, 1);

        clearFieldsAndSelection();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        bindData();
    }//GEN-LAST:event_formComponentShown

    private void btnResetPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPinActionPerformed
        int selectedRow = adminTable.getSelectedRow();
        bank.getNasabah(selectedRow).setPin("123456");
        adminTable.setValueAt(bank.getNasabah(selectedRow).getPin(), selectedRow, 4);
        labelWarning.setText("Reset Berhasil");
    }//GEN-LAST:event_btnResetPinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JLabel bankAppLabel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExitAdmin;
    private javax.swing.JButton btnResetPin;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTextField txtNamaAkhir;
    private javax.swing.JTextField txtNamaAwal;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
