/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package postTest;

import perbankan.Admin;

/**
 *
 * @author Sultan Firdaus
 */
public class AdminLoginPanel extends javax.swing.JPanel {

    private final MainFrame frame;
    private final Admin admin;

    /**
     * Creates new form AdminLoginPanel
     *
     * @param frame
     * @param admin
     */
    public AdminLoginPanel(MainFrame frame, Admin admin) {
        initComponents();
        this.frame = frame;
        this.admin = admin;
    }

    private void clearFields() {
        txtUsername.setText("");
        txtPassword.setText("");
        labelWarning.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(306, 191));
        setLayout(null);

        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(43, 54, 52, 16);

        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(43, 92, 53, 16);
        add(txtPassword);
        txtPassword.setBounds(114, 87, 147, 26);
        add(txtUsername);
        txtUsername.setBounds(114, 49, 147, 26);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(63, 131, 64, 26);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(164, 131, 69, 26);

        labelWarning.setForeground(new java.awt.Color(255, 0, 0));
        labelWarning.setText(" ");
        add(labelWarning);
        labelWarning.setBounds(114, 27, 147, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-admin.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 306, 191);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        frame.showMainPanel();
        this.setVisible(true);
        clearFields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        if (username.equals(admin.getUsername()) && password.equals(admin.getPassword())) {
            frame.showAdminPanel();
            clearFields();
        } else {
            labelWarning.setText("Username/Password salah");
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
