/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package postTest;

import java.util.ArrayList;
import perbankan.Nasabah;

/**
 *
 * @author Sultan Firdaus
 */
public class NasabahLoginPanel extends javax.swing.JPanel {

    private final MainFrame frame;
    private ArrayList<Nasabah> nasabah;

    /**
     * Creates new form NasabahLoginPanel
     *
     * @param frame
     * @param nasabah
     */
    public NasabahLoginPanel(MainFrame frame, ArrayList<Nasabah> nasabah) {
        initComponents();
        this.frame = frame;
        this.nasabah = nasabah;
    }

    private void clearFields() {
        txtNoRek.setText("");
        txtPin.setText("");
        labelWarning.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoRek = new javax.swing.JTextField();
        txtPin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(168, 131, 69, 26);

        jLabel1.setText("No. Rekening");
        add(jLabel1);
        jLabel1.setBounds(35, 54, 71, 16);

        jLabel2.setText("Pin");
        add(jLabel2);
        jLabel2.setBounds(35, 92, 71, 16);
        add(txtNoRek);
        txtNoRek.setBounds(124, 49, 147, 26);

        txtPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPinKeyTyped(evt);
            }
        });
        add(txtPin);
        txtPin.setBounds(124, 87, 147, 26);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(67, 131, 64, 26);

        labelWarning.setForeground(new java.awt.Color(255, 0, 0));
        labelWarning.setText(" ");
        add(labelWarning);
        labelWarning.setBounds(124, 27, 147, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-nasabah.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 306, 191);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        frame.showMainPanel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String noRekening = txtNoRek.getText();
        String pin = new String(txtPin.getPassword());
        int nasabahIndex = -1;

        for (int i = 0; i < nasabah.size(); i++) {
            if (nasabah.get(i).getNoRekening().equals(noRekening) && nasabah.get(i).getPin().equals(pin)) {
                nasabahIndex = i;
                break;
            }
        }
        if (nasabahIndex >= 0) {
            frame.showNasabahPanel(nasabah.get(nasabahIndex));
            clearFields();
        } else {
            labelWarning.setText("NoRek/Pin salah");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPinKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTextField txtNoRek;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
