/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package postTest;

import java.awt.Color;
import perbankan.Nasabah;

/**
 *
 * @author Sultan Firdaus
 */
public class NasabahPanel extends javax.swing.JPanel {

    private final MainFrame frame;
    private Nasabah nasabah;

    /**
     * Creates new form NasabahPanel
     *
     * @param frame
     * @param nasabah
     */
    public NasabahPanel(MainFrame frame, Nasabah nasabah) {
        initComponents();
        this.frame = frame;
        this.nasabah = nasabah;
        initLabel();
        txtUbahPin.setText(nasabah.getPin());
    }

    private void initLabel() {
        labelNamaAwal.setText(nasabah.getNamaAwal());
        labelNamaAkhir.setText(nasabah.getNamaAkhir());
        labelNoRekening.setText(nasabah.getNoRekening());
        labelSaldo.setText(String.valueOf(nasabah.getTabungan().getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExitNasabah = new javax.swing.JButton();
        bankAppLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNamaAkhir = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        labelNoRekening = new javax.swing.JLabel();
        labelNamaAwal = new javax.swing.JLabel();
        btnSetor = new javax.swing.JButton();
        btnTarik = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        btnUbahPin = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();
        txtUbahPin = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        btnExitNasabah.setText("Exit");
        btnExitNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitNasabahActionPerformed(evt);
            }
        });
        add(btnExitNasabah);
        btnExitNasabah.setBounds(338, 0, 53, 26);

        bankAppLabel.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        bankAppLabel.setText("Bank App");
        add(bankAppLabel);
        bankAppLabel.setBounds(140, 10, 99, 26);

        jLabel1.setText("No Rekening");
        add(jLabel1);
        jLabel1.setBounds(100, 60, 86, 16);

        jLabel2.setText("Nama Awal");
        add(jLabel2);
        jLabel2.setBounds(100, 88, 86, 16);

        jLabel3.setText("Nama Akhir");
        add(jLabel3);
        jLabel3.setBounds(100, 116, 86, 16);

        jLabel4.setText("Saldo");
        add(jLabel4);
        jLabel4.setBounds(100, 144, 86, 16);

        labelNamaAkhir.setText("Nama Akhir");
        add(labelNamaAkhir);
        labelNamaAkhir.setBounds(204, 116, 86, 16);

        labelSaldo.setText("Saldo");
        add(labelSaldo);
        labelSaldo.setBounds(204, 144, 86, 16);

        labelNoRekening.setText("No Rekening");
        add(labelNoRekening);
        labelNoRekening.setBounds(204, 60, 86, 16);

        labelNamaAwal.setText("Nama Awal");
        add(labelNamaAwal);
        labelNamaAwal.setBounds(204, 88, 86, 16);

        btnSetor.setText("Setor");
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });
        add(btnSetor);
        btnSetor.setBounds(110, 230, 70, 26);

        btnTarik.setText("Tarik");
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });
        add(btnTarik);
        btnTarik.setBounds(210, 230, 70, 26);

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        add(txtSaldo);
        txtSaldo.setBounds(141, 196, 108, 26);

        btnUbahPin.setText("Ubah Pin");
        btnUbahPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPinActionPerformed(evt);
            }
        });
        add(btnUbahPin);
        btnUbahPin.setBounds(154, 262, 82, 26);

        labelWarning.setText(" ");
        add(labelWarning);
        labelWarning.setBounds(141, 174, 108, 16);

        txtUbahPin.setEnabled(false);
        txtUbahPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbahPinKeyTyped(evt);
            }
        });
        add(txtUbahPin);
        txtUbahPin.setBounds(130, 290, 128, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-nasabah.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 390, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitNasabahActionPerformed
        frame.showMainPanel();
    }//GEN-LAST:event_btnExitNasabahActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        if (txtSaldo.getText().isEmpty()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Masukkan Nominal");
            return;
        }
        int jumlahSetor = Integer.parseInt(txtSaldo.getText());
        nasabah.getTabungan().simpanUang(jumlahSetor);
        labelWarning.setForeground(Color.GREEN);
        labelWarning.setText("Setor Sukses");
        labelSaldo.setText(String.valueOf(nasabah.getTabungan().getSaldo()));
        txtSaldo.setText("");
    }//GEN-LAST:event_btnSetorActionPerformed

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikActionPerformed
        if (txtSaldo.getText().isEmpty()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Masukkan Nominal");
            return;
        }
        int jumlahAmbil = Integer.parseInt(txtSaldo.getText());
        if (!nasabah.getTabungan().ambilUang(jumlahAmbil)) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Saldo Tidak Cukup");
            return;
        }
        labelWarning.setForeground(Color.GREEN);
        labelWarning.setText("Tarik Sukses");
        labelSaldo.setText(String.valueOf(nasabah.getTabungan().getSaldo()));
        txtSaldo.setText("");
    }//GEN-LAST:event_btnTarikActionPerformed

    private void btnUbahPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPinActionPerformed
        if (btnUbahPin.getText().equals("Ubah Pin")) {
            txtUbahPin.setEnabled(true);
            btnUbahPin.setText("Simpan");
        } else {
            String newPin = new String(txtUbahPin.getPassword());
            if (newPin.isEmpty()) {
                labelWarning.setForeground(Color.RED);
                labelWarning.setText("Pin Kosong!!");
                return;
            }
            nasabah.setPin(newPin);
            labelWarning.setForeground(Color.GREEN);
            labelWarning.setText("Pin Disimpan");
            txtUbahPin.setEnabled(false);
            btnUbahPin.setText("Ubah Pin");
        }
    }//GEN-LAST:event_btnUbahPinActionPerformed

    private void txtUbahPinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbahPinKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUbahPinKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankAppLabel;
    private javax.swing.JButton btnExitNasabah;
    private javax.swing.JButton btnSetor;
    private javax.swing.JButton btnTarik;
    private javax.swing.JButton btnUbahPin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNamaAkhir;
    private javax.swing.JLabel labelNamaAwal;
    private javax.swing.JLabel labelNoRekening;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JPasswordField txtUbahPin;
    // End of variables declaration//GEN-END:variables
}
