/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiFrame;

/**
 *
 * @author Sultan Firdaus
 */
public class Frame4 extends javax.swing.JFrame {

    private MultiFrame multiFrame;
    private String frameName;
    private String previousFrameName;

    public Frame4(MultiFrame multiFrame, String frameName, String previousFrameName) {
        initComponents();
        this.multiFrame = multiFrame;
        this.frameName = frameName;
        this.previousFrameName = previousFrameName;
        labelCurrentFrame.setText(frameName);
        labelPreviousFrame.setText(previousFrameName);
    }

    public String getFrameName() {
        return frameName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCurrentFrame = new javax.swing.JLabel();
        labelPreviousFrame = new javax.swing.JLabel();
        btnFrame1 = new javax.swing.JButton();
        btnFrame2 = new javax.swing.JButton();
        btnFrame3 = new javax.swing.JButton();
        btnFrame4 = new javax.swing.JButton();
        btnFrame5 = new javax.swing.JButton();
        btnFrame6 = new javax.swing.JButton();
        btnFrame7 = new javax.swing.JButton();
        btnFrame8 = new javax.swing.JButton();
        btnFrame9 = new javax.swing.JButton();
        btnFrame10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Current Frame     : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Previous Frame   : ");

        labelCurrentFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCurrentFrame.setText("label");

        labelPreviousFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPreviousFrame.setText("label");

        btnFrame1.setText("Frame 1");
        btnFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame1ActionPerformed(evt);
            }
        });

        btnFrame2.setText("Frame 2");
        btnFrame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame2ActionPerformed(evt);
            }
        });

        btnFrame3.setText("Frame 3");
        btnFrame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame3ActionPerformed(evt);
            }
        });

        btnFrame4.setText("Frame 4");
        btnFrame4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame4ActionPerformed(evt);
            }
        });

        btnFrame5.setText("Frame 5");
        btnFrame5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame5ActionPerformed(evt);
            }
        });

        btnFrame6.setText("Frame 6");
        btnFrame6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame6ActionPerformed(evt);
            }
        });

        btnFrame7.setText("Frame 7");
        btnFrame7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame7ActionPerformed(evt);
            }
        });

        btnFrame8.setText("Frame 8");
        btnFrame8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame8ActionPerformed(evt);
            }
        });

        btnFrame9.setText("Frame 9");
        btnFrame9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame9ActionPerformed(evt);
            }
        });

        btnFrame10.setText("Frame 10");
        btnFrame10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrame10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreviousFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCurrentFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrame1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrame6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrame10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelCurrentFrame))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelPreviousFrame))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrame1)
                    .addComponent(btnFrame2)
                    .addComponent(btnFrame3)
                    .addComponent(btnFrame4)
                    .addComponent(btnFrame5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrame6)
                    .addComponent(btnFrame7)
                    .addComponent(btnFrame8)
                    .addComponent(btnFrame9)
                    .addComponent(btnFrame10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame2ActionPerformed
        multiFrame.showFrame2(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame2ActionPerformed

    private void btnFrame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame3ActionPerformed
        multiFrame.showFrame3(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame3ActionPerformed

    private void btnFrame4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame4ActionPerformed
        multiFrame.showFrame4(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame4ActionPerformed

    private void btnFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame1ActionPerformed
        multiFrame.showFrame1(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame1ActionPerformed

    private void btnFrame5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame5ActionPerformed
        multiFrame.showFrame5(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame5ActionPerformed

    private void btnFrame6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame6ActionPerformed
        multiFrame.showFrame6(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame6ActionPerformed

    private void btnFrame7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame7ActionPerformed
        multiFrame.showFrame7(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame7ActionPerformed

    private void btnFrame8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame8ActionPerformed
        multiFrame.showFrame8(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame8ActionPerformed

    private void btnFrame9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame9ActionPerformed
        multiFrame.showFrame9(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame9ActionPerformed

    private void btnFrame10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrame10ActionPerformed
        multiFrame.showFrame10(this.frameName);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnFrame10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrame1;
    private javax.swing.JButton btnFrame10;
    private javax.swing.JButton btnFrame2;
    private javax.swing.JButton btnFrame3;
    private javax.swing.JButton btnFrame4;
    private javax.swing.JButton btnFrame5;
    private javax.swing.JButton btnFrame6;
    private javax.swing.JButton btnFrame7;
    private javax.swing.JButton btnFrame8;
    private javax.swing.JButton btnFrame9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCurrentFrame;
    private javax.swing.JLabel labelPreviousFrame;
    // End of variables declaration//GEN-END:variables
}
