/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiFrameCLass;

/**
 *
 * @author Sultan Firdaus
 */
public class BaseFrame extends javax.swing.JFrame {

    private MultiFrame multiFrame;
    private String frameName;
    private String prevFrameName;

    public BaseFrame(MultiFrame multiFrame, String frameName) {
//        initComponents();
        this.multiFrame = multiFrame;
        this.frameName = frameName;
        this.prevFrameName = "Ga Ada";
    }

    public void setPrevFrameName(String name) {
        this.prevFrameName = name.isEmpty() ? "Ga Ada" : name;
    }

    public MultiFrame getMultiFrame() {
        return multiFrame;
    }

    public String getFrameName() {
        return frameName;
    }

    public String getPrevFrameName() {
        return prevFrameName;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
