package postTest;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import services.CashierService;
import shm.DetailTransaksi;

/**
 *
 * @author Sultan Firdaus
 */
public class InsertPanel extends javax.swing.JPanel {

    private final Frame frame;
    private final ArrayList<DetailTransaksi> detailTransaksi;

    /**
     * Creates new form InsertPanel
     *
     * @param frame
     */
    public InsertPanel(Frame frame) {
        initComponents();
        this.frame = frame;
        this.detailTransaksi = new ArrayList<>();
        this.makeTableListener();
    }

    private boolean merkMobilValidation() {
        if (txtMerkMobil.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean platNomorValidation() {
        if (txtPlatNomor.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean dateChooserValidation() {
        try {
            new SimpleDateFormat("dd-MM-yyyy").format(dateChooser.getDate());
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void makeTableListener() {
        layananTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            boolean isSelected = !layananTable.getSelectionModel().isSelectionEmpty();
            btnDelete.setEnabled(isSelected);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMerkMobil = new javax.swing.JTextField();
        txtPlatNomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dropdownStatusSelesai = new javax.swing.JComboBox<>();
        dropdownStatusPembayaran = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        layananTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLayanan = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnTambahLayanan = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SAHABAT MOBIL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Merk Mobil");

        jLabel3.setText("Plat Nomor");

        jLabel4.setText("Tanggal");

        dateChooser.setDateFormatString("dd-MM-yyyy");

        jLabel5.setText("Status Selesai");

        dropdownStatusSelesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Selesai" }));

        dropdownStatusPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Lunas" }));

        jLabel6.setText("Status Pembayaran");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        layananTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Layanan", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(layananTable);
        if (layananTable.getColumnModel().getColumnCount() > 0) {
            layananTable.getColumnModel().getColumn(0).setResizable(false);
            layananTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setText("Layanan");

        jLabel8.setText("Harga");

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        btnTambahLayanan.setText("+ Tambah Layanan");
        btnTambahLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahLayananActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarning.setText(" ");
        labelWarning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMerkMobil)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPlatNomor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHarga))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dropdownStatusPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnTambahLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(dropdownStatusSelesai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(343, 343, 343)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCancel)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(labelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWarning)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtPlatNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMerkMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dropdownStatusSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dropdownStatusPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txtLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTambahLayanan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        frame.loadPanel(frame.getMainPanel());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!merkMobilValidation()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Merk Kosong!!!");
            return;
        }
        if (!platNomorValidation()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Plat Nomor Kosong!!!");
            return;
        }
        if (!dateChooserValidation()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Tanggal Kosong!!!");
            return;
        }
        if (detailTransaksi.isEmpty()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Layanan Kosong");
            return;
        }

        CashierService.getCashier().tambahTransaksi(txtMerkMobil.getText(),
                txtPlatNomor.getText(),
                new SimpleDateFormat("dd-MM-yyyy").format(dateChooser.getDate()),
                dropdownStatusSelesai.getSelectedItem().toString(),
                dropdownStatusPembayaran.getSelectedItem().toString()
        );
        CashierService.getCashier().getOneTransaksi(CashierService.getCashier().getJumlahTransaksi() - 1).setDetailTransaksi(detailTransaksi);

        this.setVisible(false);
        frame.loadPanel(frame.getMainPanel());
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnTambahLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLayananActionPerformed
        if (txtHarga.getText().isEmpty() || txtLayanan.getText().isEmpty()) {
            labelWarning.setForeground(Color.RED);
            labelWarning.setText("Layanan Kosong!!!");
            return;
        }

        DefaultTableModel tableModel = (DefaultTableModel) layananTable.getModel();
        detailTransaksi.add(new DetailTransaksi(Integer.parseInt(txtHarga.getText()), txtLayanan.getText()));
        Object[] newRowData = {
            detailTransaksi.get(tableModel.getRowCount()).getKerusakan(),
            "Rp " + String.valueOf(detailTransaksi.get(tableModel.getRowCount()).getHarga())
        };
        tableModel.addRow(newRowData);

        txtHarga.setText("");
        txtLayanan.setText("");
        layananTable.clearSelection();
    }//GEN-LAST:event_btnTambahLayananActionPerformed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = layananTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) layananTable.getModel();
        detailTransaksi.remove(selectedRow);
        tableModel.removeRow(selectedRow);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTambahLayanan;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<String> dropdownStatusPembayaran;
    private javax.swing.JComboBox<String> dropdownStatusSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTable layananTable;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtLayanan;
    private javax.swing.JTextField txtMerkMobil;
    private javax.swing.JTextField txtPlatNomor;
    // End of variables declaration//GEN-END:variables
}
